name: tour_guide
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  supabase_flutter: ^2.10.0
  url_launcher: ^6.1.10
  image_picker: ^1.0.4
  razorpay_flutter: ^1.3.6
  intl: ^0.20.2
  file_picker: ^8.0.0
  geolocator: ^10.1.0
  geocoding: ^2.2.0
  google_fonts: ^6.2.1
  mailer: ^6.5.0
  cloudinary: ^1.2.0
  gradient_borders: ^1.0.0
  confetti: ^0.7.0
  video_player: ^2.9.0
  smooth_page_indicator: ^1.1.0  
  fl_chart: ^0.69.0
  flutter_screenutil: ^5.9.3
  flutter_markdown: ^0.7.2
  seo_renderer: ^0.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sample.jpg
    - assets/tour1.jpg
    - assets/tour2.jpg
    - assets/tour3.jpg
    - assets/tour4.jpg
    - assets/banner.jpg
    - assets/Paris.jpg
    - assets/Dubai.jpg
    - assets/NewYork.jpg
    - assets/Rio.jpg
    - assets/Bali.jpg
    - assets/Miami.jpg
    - assets/Sumatra.jpg
    - assets/Pattaya.jpg
    - assets/Mumbai.jpg
    - assets/Singapore.jpg
    - assets/Citimart.jpg
    - assets/default_avatar.png
    - assets/login.png
    - assets/bg_home.jpg
    - assets/login.jpg
    - assets/cover_image.jpg
    - assets/yo.jpg
    - assets/sea.jpg
    - assets/mountain1.jpg
    - assets/mountain.jpg
    - assets/Victoria-Memorial.jpg
    - assets/Pareshnath-Jain-Temple.jpg
  # - assets/default_.png
